### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Orava2** [imniko/SetDPI#11]
New version 1.0 doesn't work on Windows 10 64 Enterprise. Version 0.2 is working ok.

![kuva](https://user-images.githubusercontent.com/32876893/217224629-dbcbba18-dffd-455c-aa3e-9ec8eaa9820b.png)

![kuva](https://user-images.githubusercontent.com/32876893/217224405-38b84f9e-b2ac-4cab-8f0a-1b1c07a47939.png)

**Comment by imniko** [comment]
Can you move the exe on some other directory except C? Or maybe unlock the exe? or download latest VS redistributable from here https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Orava2** [comment]
Sorry. This was my mistake. Two computers i used to test SetDPI had F-Secure Antivirus intalled. Deep Guard blocked the execution but no additional info was shown.

**Comment by imniko** [comment]
Alright, closing it then. Though I'd recommend compiling the project yourself if possible.
