### ISSUE TITLE
AHK Key shortcut comments don't match actual hotkey

### ISSUE THREAD

**Issue by AtomicSource** [imniko/SetDPI#3]
In the AutoHotKey script included, there are two hotkeys:

AHK code | Key combination
---------- | -------------
`^#F1::` | Ctrl + Win + F1
`^#F2::` | Ctrl + Win + F2

However the comments above each suggest a different key combo. 

```
; win + alt + F1 toggles main monitor between 2 scale values 
^#F1::
```
and 
```
; win + alt + F2 sets 2nd monitor to a scale of 150
^#F2::
```

This is confusing for someone trying to get this to work after downloading.  The comments should match the coded shortcuts.

**Comment by AtomicSource** [comment]
I would submit a pull request for this simple fix, but I can't find the AHK script in the code, I'm guessing it's not included? If so, I would suggest adding it.

Otherwise, thanks so much @imniko for making this very useful cmd tool!

**Comment by AtomicSource** [comment]
Here's the AHK documentation showing the basic key symbols:
[Keys and their mysterious symbols](https://www.autohotkey.com/docs/Tutorial.htm#s21)

**Comment by imniko** [comment]
Sorry, that was a silly error from my end. I have updated the ahk file and issued a new release.
