### ISSUE TITLE
Custom scale factor not supported in Windows 11

### ISSUE THREAD

**Issue by unknown-user-account** [imniko/SetDPI#5]
Windows 11 supports a custom scale factor. The application should be updated to support it.

**Comment by rakibul-gd** [comment]
I haven't updated to windows 11 yet, so don't know when I will be able to update it to support windows 11 or that its even possible to do it.

**Comment by imniko** [comment]
I haven't updated to windows 11 yet, so not sure when I will be able to update it for win 11, or cant say that the code will even work on windows 11 at all.

**Comment by breaks-r-mine** [comment]
Sry mr unknown user, dpiscale works perfect on 22000.675 ! and custom scale says microsoft its unsupported.

Love this app !

**Comment by unknown-user-account** [comment]
> 
The application works normally on Windows 11 it just doesn't support the new fractional scaling capability.

**Comment by unknown-user-account** [comment]
> I haven't updated to windows 11 yet, so not sure when I will be able to update it for win 11, or cant say that the code will even work on windows 11 at all.

The application works fine on Windows 11. 



> Sry mr unknown user, dpiscale works perfect on 22000.675 ! and custom scale says microsoft its unsupported.
> 
> Love this app !

I don't think you understand the issue. I meant that it should support the new fractional scaling capability. Currently it's limited to multiples of 25 (100, 125, 150 etc.) whereas Windows 11 let's you choose values in between those (like 111, 112, etc).

**Comment by imniko** [comment]
I see, this program gets a list of recommended scaling options from OS, and only matching scale value are selected, maybe adding a parameter to ignore default scaling option might do the trick. Still I am not sure that will work perfectly though. Might give it a shot, this weekend but no ETA unfortunately.
