### ISSUE TITLE
Option to display current dpi value

### ISSUE THREAD

**Issue by X1pheR** [imniko/SetDPI#6]
Hi! Must say... I love the utility. I was looking for a way to change the dpi setting from command line for quite some time now and then I found your utility. I want to use it in an AHK script. Could you add an option to output the current dpi value?

**Comment by jameswilliamknight** [comment]
I'm not fluent in C++, but I second this request! Could we expose [this](https://github.com/imniko/SetDPI/blob/d833b3cb2cf7c01a5985ef0f45a2d2cf01168c64/DpiHelper.h#L99) to the CLI?

**Comment by imniko** [comment]
FYI there is an ahk script in the release section. So you the program to return the current monitor scale value as an exit code? Like 

```
> SetDPI.exe -cdpi 
> 100 
```
I am also not much of a C++ guy, but if that's what you want I could do that.

**Comment by breaks-r-mine** [comment]
first of all imniko, amazing script the only one that worked 100% from Windows 10 to 11 without destroying the settings menu !!!

iam also interesting in reading the current dpi, at the moment i do it with powershell but its tricky. If u can implement it in your script i can drop my ps1 would be nice.


my Current PS1 if someone needed:

Add-Type @'
using System; 
using System.Runtime.InteropServices;
using System.Drawing;

public class DPI {  
  [DllImport("gdi32.dll")]
  static extern int GetDeviceCaps(IntPtr hdc, int nIndex);

  public enum DeviceCap {
  VERTRES = 10,
  DESKTOPVERTRES = 117
  } 

  public static float scaling() {
  Graphics g = Graphics.FromHwnd(IntPtr.Zero);
  IntPtr desktop = g.GetHdc();
  int LogicalScreenHeight = GetDeviceCaps(desktop, (int)DeviceCap.VERTRES);
  int PhysicalScreenHeight = GetDeviceCaps(desktop, (int)DeviceCap.DESKTOPVERTRES);

  return (float)PhysicalScreenHeight / (float)LogicalScreenHeight;
  }
}
'@ -ReferencedAssemblies 'System.Drawing.dll' -ErrorAction Stop
Return [DPI]::scaling() * 100
