### ISSUE TITLE
Windows 11 error: This app can't run on your PC

### ISSUE THREAD

**Issue by anoop0** [imniko/SetDPI#7]
Getting following error Windows 11: Home edition

![image](https://user-images.githubusercontent.com/3315158/193394547-17b33ab8-3cf6-44e5-b2b6-1fa5e2699e57.png)

**Comment by imniko** [comment]
I am still on windows 10, so cant diagnose the issue rn. If anyone has a solution, please make a PR.

**Comment by imniko** [comment]
Maybe AV was blocking the executable. Also I tried the latest version on a VM win 11, and it worked. It just does not support custom scale, and I don't think I have the coding knowledge to make that work.
